### PR TITLE
Added badges to readme + Identicon preview

### PR DESCRIPTION
**Pull request by LucaCappelletti94**
Hi, great library!

I wanted to see a preview of its results, so I thought it best to add it to the README for other users.

While I was at it, I also added the badges for the docs and crate.

Luca

### CODE REVIEW

**Comment by conways-glider** [comment]
I love these suggestions!

I think I might change one of the example inputs just so that we show off a wider color palette. I'll take a look at a few different inputs and might suggest changes based on that.

**Comment by LucaCappelletti94** [comment]
Maybe instead of fully randomizing colors, a nice option may be to pick at random from [a pantone color list like matplotlib](https://matplotlib.org/stable/_images/sphx_glr_named_colors_002_2_00x.png)?

I can add the hexas fairly quickly.

**Comment by conways-glider** [comment]
I think optionally supporting setting the color would be a good idea, but I think the default behavior should still be based on the hash of the input.

**Comment by conways-glider** [comment]
I've been toying with the idea of allowing users to optionally select their own colors. Adding palettes and theming to this project is a great idea!

I think I'll follow up with that in another MR and then post images of the palettes/themes added, along with documentation on how to make your own.

**Review by conways-glider — APPROVED** [review]
~Merging~ Approving. I'll follow up with an MR soon to add themes, along with custom themes, while preserving a random pastel option (the current behavior) as default.

I'll merge as soon as checks pass.

**Comment by conways-glider** [comment]
@LucaCappelletti94 
I've filed an issue for theme/palette design - #36

**Pull request merged**
